[package]
name = "lepton_jpeg"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
description = "Rust port of the Lepton JPEG compression library"
readme = "README.md"
repository = "https://github.com/microsoft/lepton_jpeg_rust"
license = "Apache-2.0"
exclude = [
    "images/*",
    "tests/*",
]

[profile.release]
debug=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
byteorder = ">=1.4.3"
flate2 = ">=1.0"
default-boxed = "0.2.0"
anyhow = { version=">=1.0.0", features = ["backtrace"]}
wide = "0.7.5"

[dev-dependencies]
rstest = "0.16.0"

[[bin]]
name = "lepton_jpeg_util"
path = "src/main.rs"

[lib]
crate-type = ["cdylib","lib"]

